# Generated by Django 5.2.8 on 2025-11-24 20:54

import django.db.models.deletion
import varsdaa.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varsdaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', varsdaa.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='varsdaa.desk'),
        ),
    ]
