# Generated by Django 5.2.8 on 2025-11-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('varsdaa', '0002_alter_user_managers_alter_registration_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='varsdaa.office'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('alphanumeric_serial_number', models.CharField(max_length=255)),
                ('user_updated_at', models.DateTimeField()),
                ('desk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='varsdaa.desk')),
                (
                    'user',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
