# Generated by Django 5.2.8 on 2025-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('varsdaa', '0003_user_office_user_office_updated_at_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='product_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='display',
            name='user_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
